const materias = [
    {materia: 'Multimedios', tipo :'optativa'},
    {materia: 'Diseno y desarrollo de videojuegos', tipo:'optativa'},
    {materia: 'Comercio electronico', tipo:'optativa'},
    {materia: 'Graficas por computadora', tipo:'optativa'},
    {materia: 'Persona y proyecto de vida', tipo:'optativa'},
    {materia: 'Propuesta cristiana', tipo:'optativa'},
    {materia: 'Arte, cultura y sociedad', tipo:'optativa'},
    {materia: 'Responsabilidad social y mundo contemporaneo', tipo:'optativa'},
    {materia: 'Apreciacion cinematografica', tipo:'optativa'},
    {materia: 'Tecnicas de investigacion', tipo:'optativa'},
    {materia: 'Gestion de proyectos informaticos', tipo:'optativa'},
    {materia: 'Sistemas de informacion integral', tipo:'optativa'},

    {materia: 'Redes III', tipo:'especialidad', especialidad: 'Telecomunicaciones'},
    {materia: 'Redes IV', tipo:'especialidad', especialidad: 'Telecomunicaciones'},
    {materia: 'Servicios de red', tipo:'especialidad', especialidad: 'Telecomunicaciones'},
    {materia: 'Seguridad y auditoria de sistemas', tipo:'especialidad', especialidad: 'Telecomunicaciones'},

    {materia: 'Programacion web I', tipo:'especialidad', especialidad: 'Desarrollodeaplicaciones'},
    {materia: 'Programacion web II', tipo:'especialidad', especialidad: 'Desarrollodeaplicaciones'},
    {materia: 'Programacion de sistemas moviles', tipo:'especialidad', especialidad: 'Desarrollodeaplicaciones'},
    {materia: 'Programacion de sistemas moviles II', tipo:'especialidad', especialidad: 'Desarrollodeaplicaciones'},
        
    {materia: 'Electronica', tipo:'especialidad', especialidad: 'Circuitosyelectronica'},
    {materia: 'Teoria de circuitos', tipo:'especialidad', especialidad: 'Circuitosyelectronica'},
    {materia: 'Sensores y actuadores', tipo:'especialidad', especialidad: 'Circuitosyelectronica'},
    {materia: 'Sensores y actuadores II', tipo:'especialidad', especialidad: 'Circuitosyelectronica'},    

    {materia: 'Introduccion a la programacion', tipo:'formacionprofesional'},
    {materia: 'Tecnologias de informacion y comunicacion', tipo:'formacionprofesional'},
    {materia: 'Programacion I', tipo:'formacionprofesional'},
    {materia: 'Programacion II', tipo:'formacionprofesional'},
    {materia: 'Logica digital', tipo:'formacionprofesional'},
    {materia: 'Estructura de datos', tipo:'formacionprofesional'},
    {materia: 'Bases de datos', tipo:'formacionprofesional'},
    {materia: 'Redes I', tipo:'formacionprofesional'},
    {materia: 'Lenguaje ensamblador', tipo:'formacionprofesional'},
    {materia: 'Entornos de desarrollo integrado', tipo:'formacionprofesional'},
    {materia: 'Base de datos II', tipo:'formacionprofesional'},
    {materia: 'Redes II', tipo:'formacionprofesional'},
    
    {materia: 'Metodologia de la investigacion', tipo:'troncocomun'},
    {materia: 'Administracion', tipo:'troncocomun'},
    {materia: 'Contabilidad financiera', tipo:'troncocomun'},
    {materia: 'Tecnicas de investigacion', tipo:'troncocomun'},
    {materia: 'Ingles', tipo:'troncocomun', opcion:'si'},
    {materia: 'Desarrollo de emprendedores', tipo:'troncocomun'},
    {materia: 'Administracion de las tecnologias de informacion', tipo:'troncocomun'},
]

export {materias}