const materias = [
    {materia: 'Multimedios', tipo :'optativa'},
    {materia: 'Disenoydesarrollodevideojuegos', tipo:'optativa'},
    {materia: 'Comercioelectronico', tipo:'optativa'},
    {materia: 'Graficasporcomputadora', tipo:'optativa'},
    {materia: 'Personayproyectodevida', tipo:'optativa'},
    {materia: 'Propuestacristiana', tipo:'optativa'},
    {materia: 'Arteculturaysociedad', tipo:'optativa'},
    {materia: 'Responsabilidadsocialymundocontemporaneo', tipo:'optativa'},
    {materia: 'Apreciacioncinematografica', tipo:'optativa'},
    {materia: 'Tecnicasdeinvestigacion', tipo:'optativa'},
    {materia: 'Gestiondeproyectosinformaticos', tipo:'optativa'},
    {materia: 'Sistemasdeinformacionintegral', tipo:'optativa'},

    {materia: 'RedesIII', tipo:'especialidad'},
    {materia: 'RedesIV', tipo:'especialidad'},
    {materia: 'Serviciosdered', tipo:'especialidad'},
    {materia: 'Seguridadyauditoriadesistemas', tipo:'especialidad'},

    {materia: 'ProgramacionwebI', tipo:'especialidad'},
    {materia: 'ProgramacionwebII', tipo:'especialidad'},
    {materia: 'Programaciondesistemasmoviles', tipo:'especialidad'},
    {materia: 'ProgramaciondesistemasmovilesII', tipo:'especialidad'},
        
    {materia: 'Electronica', tipo:'especialidad'},
    {materia: 'Teoriadecircuitos', tipo:'especialidad'},
    {materia: 'Sensoresyactuadores', tipo:'especialidad'},
    {materia: 'SensoresyactuadoresII', tipo:'especialidad'},    

    {materia: 'Introduccionalaprogramacion', tipo:'formacionprofesional'},
    {materia: 'Tecnologiasdeinformacionycomunicacion', tipo:'formacionprofesional'},
    {materia: 'ProgramacionI', tipo:'formacionprofesional'},
    {materia: 'ProgramacionII', tipo:'formacionprofesional'},
    {materia: 'Logicadigital', tipo:'formacionprofesional'},
    {materia: 'Estructuradedatos', tipo:'formacionprofesional'},
    {materia: 'Basesdedatos', tipo:'formacionprofesional'},
    {materia: 'RedesI', tipo:'formacionprofesional'},
    {materia: 'Lenguajeensamblador', tipo:'formacionprofesional'},
    {materia: 'Entornosdedesarrollointegrado', tipo:'formacionprofesional'},
    {materia: 'BasededatosII', tipo:'formacionprofesional'},
    {materia: 'RedesII', tipo:'formacionprofesional'},
    
    {materia: 'Metodologiadelainvestigacion', tipo:'troncocomun'},
    {materia: 'Administracion', tipo:'troncocomun'},
    {materia: 'Contabilidadfinanciera', tipo:'troncocomun'},
    {materia: 'Tecnicasdeinvestigacion', tipo:'troncocomun'},
    {materia: 'Ingles', tipo:'troncocomun', opcion:'si'},
    {materia: 'Desarrollodeemprendedores', tipo:'troncocomun'},
    {materia: 'Administraciondelastecnologiasdeinformacion', tipo:'troncocomun'},
]